name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # This ensures that the snake image updates every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: INDRAMANI538  # Replace with your GitHub username
          outputs: dist
      - name: Upload animation
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist
